### ISSUE TITLE
reproduce the ablation results in Figure 1

### ISSUE THREAD

**Issue by SherrySwift** [SqueezeAILab/KVQuant#2]
Thanks for your great works! 
I want to reproduce the ablation results presented in paper Figure 1. According to Figure 1, Per-Channel Key Quantization + Pre-RoPE Key Quantization yields PPL=6.34 in Llama-7b (3bit) setting. However, I got PPL=6.71 by running the following command:
`CUDA_VISIBLE_DEVICES=0 python llama_simquant.py <path-to-llama-7b-hf> --abits 4 --nsamples 16 --seqlen 2048 --quantize --quantizer_path quantizers.pickle ;`
can't figure out why. Would you please give me some advice? Thank you so much!

**Comment by chooper1** [comment]
Thank you for your interest in our work! 

The reduced accuracy that you are seeing here is because we used an unclamped zero-point when performing per-channel integer quantization with keys. For the baseline experiments (which use per-token quantization), there isn’t any accuracy difference between using a clamped or unclamped zero-point, so we used the clamped zero-point since it can be stored more compactly. However, for per-channel quantization, we observed that using an unclamped zero-point yielded significantly higher accuracy.

The current codebase is not set up to replicate all of the ablations and baseline results from the paper (for example, it clamps the zero-point by default for integer quantization). We plan to update the codebase in the future to allow for replicating the remaining experiments in the paper!
